name: node-graphql-api
recipe: mean
config:
  node: 12
  build:
    - npm install
  command: npm start
  database: mongo:4.0
  globals: []
  port: '3000'
  ssl: false
services:
  mysql:
    type: mysql
    overrides:
      image: bitnami/mysql:5.7.28
    creds:
      user: root
      password: root
      database: blog